### ISSUE TITLE
ADR: Scripting Language Choice

### ISSUE THREAD

**Issue by mdekrey** [PrincipleStudios/PrincipleTools#19]
We typically use Powershell Core for scripting languages (such as the [git branching tools](https://github.com/PrincipleStudios/scalable-git-branching-tools)).

Write an ADR stating why.

**Comment by yumaikas** [comment]
Some thoughts:

We have deep .NET expertise on the team, where we don't for comparable languages (bash, python, ruby).
Also, I'd argue that Powershell is somewhat handier for a lot of our scripting tasks than node.js, which would be the other common contender here.
